[project]
name = "ghde"
version = "0.1.0"
description = "Greenhouse Data Extractor"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fire>=0.7.0",
    "requests>=2.32.3",
    "structlog>=25.2.0",
]
